spring:
    datasource:
        
        username: erickmarques
        password: erickmarques
        url: jdbc:mysql://pridedevdatabase.c3lbe0bvk2jp.us-east-1.rds.amazonaws.com/erickmarques
         
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
            

